In [62]:
import numpy as np

In [63]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [64]:
print ( *arr)

1 2 3 4 5 6 7 8 9 10 11 12


In [65]:
arr.shape

(12,)

In [66]:
a2d = np.array([   [1,2,3,4,5,6],
                   [7,8,9,10,11,12]
                ])

In [67]:
print(*a2d)

[1 2 3 4 5 6] [ 7  8  9 10 11 12]


In [68]:
a2d.shape

(2, 6)

In [69]:
a2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [70]:
a2d.shape

(2, 6)

In [71]:
a3d = np.array( [
                   [
                       [1,2,3],
                       [1,2,3]
                    ]
                ]
              )

In [72]:
a3d.shape

(1, 2, 3)

In [73]:
a = arr.reshape(4,3,1)

In [74]:
a.shape

(4, 3, 1)

In [75]:
a

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

**UNPACKING**


In [76]:
def addNum(a,b,c):
    ans = a + b + c
    return ans



In [77]:
#https://www.youtube.com/watch?v=Eztf8MU47kM&ab_channel=Bytive

argv = [1,1,1]
x = addNum(*argv)

print( x)


3


In [81]:
import pandas as pd
import numpy as np

In [80]:
data = pd.read_csv('./fashion-mnist_train.csv')
data.shape

(60000, 785)

In [86]:
arr = np.array(data)
arr = arr[:,1:]

In [84]:
arr.shape

(60000, 785)

In [87]:
rows = arr.shape[0]
r = arr.reshape(rows,*(28,28,1))

In [88]:
r.shape

(60000, 28, 28, 1)

In [103]:
y_train = np.array(data)[:,0]

In [104]:
y_train.shape

(60000,)

In [105]:
y_train

array([2, 9, 6, ..., 8, 8, 7], dtype=int64)