In [1]:
import numpy as np

In [2]:
#ndim, shape, size, dtype


In [4]:
#int list
sales = [0,5,155,518,0,1827,616,317,325]

sales_np_array = np.array(sales)

In [7]:
sales_np_array

array([   0,    5,  155,  518,    0, 1827,  616,  317,  325])

In [8]:
sales

[0, 5, 155, 518, 0, 1827, 616, 317, 325]

In [11]:
print(f"ndim: {sales_np_array.ndim}");
print(f"shape: {sales_np_array.shape}");
print(f"size: {sales_np_array.size}");
print(f"dtype: {sales_np_array.dtype}");

ndim: 1
shape: (9,)
size: 9
dtype: int64


In [12]:
#two dimentional list
s = [[1,2,3,4,5],[6,7,8,9,10]]
snp = np.array(s)

In [13]:
snp.shape

(2, 5)

In [16]:
snp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
snp.size

10

In [24]:
result = snp[0]*snp[1]

In [25]:
result

array([ 6, 14, 24, 36, 50])

In [27]:
#Create array
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [33]:
r = range(5)
for i in r:
    print(i)

0
1
2
3
4


In [48]:
array2d = np.array([range(5),range(5),range(5)])

In [51]:
array2d.shape

(3, 5)